require("dotenv").config();

module.exports = {
  MONGO_USERNAME_SANDBOX: process.env.MONGO_USERNAME_SANDBOX,
  MONGO_PASSWORD_SANDBOX: process.env.MONGO_PASSWORD_SANDBOX,
  MONGO_DATABASE_NAME_SANDBOX: process.env.MONGO_DATABASE_NAME_SANDBOX,
  DARWINBOX_USERNAME: process.env.DARWINBOX_USERNAME,
  DARWINBOX_PASSWORD: process.env.DARWINBOX_PASSWORD,
  DARWINBOX_API_KEY: process.env.DARWINBOX_API_KEY,
  DARWINBOX_DATASET_KEY: process.env.DARWINBOX_DATASET_KEY,
  DARWINBOX_BASE_URL: process.env.DARWINBOX_BASE_URL,
  CAPILLARY_JWT_SECRET: process.env.CAPILLARY_JWT_SECRET,
};
